- name: Install Code Server
  hosts: all
  vars: 
    cs_archive: https://github.com/coder/code-server/releases/download/v4.9.1/code-server-4.9.1-linux-amd64.tar.gz
    cs_dir: /usr/local/opt
    cs_unpacked: code-server-4.9.1-linux-amd64 
  tasks:
  - name: Update OS
    apt:
      update_cache: yes
      upgrade: yes

  - name: Create Directory
    file:
      path: "{{item}}"
      state: directory
      mode: '0755'
    loop:
    - "{{ cs_dir }}"
    - /var/lib/code-server

  - name: Check dirs exist
    stat:
      path: "{{ cs_dir }}/{{ cs_unpacked }}"
    register: dir 

  - name: Download and unzip code-server 
    unarchive:
      src: "{{ cs_archive }}"
      dest: "{{ cs_dir }}"
      remote_src: yes
    when: not dir.stat.exists

  - name: Link directory and binary
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop:
    - src: "{{ cs_dir }}/{{ cs_unpacked }}"
      dest: "/usr/lib/code-server"
    - src: "{{ cs_dir }}/{{ cs_unpacked }}/bin/code-server"
      dest: "/usr/lib/code-server"

  - name: Generate cs service
    template: 
      src: code-server.service.j2
      dest: /lib/systemd/system/code-server.service

  - name: Enable cs service
    systemd:
      name: code-server
      daemon_reload: true
      enabled: true
      state: started

- name: Install NGINX
  hosts: all
  tasks:
  - name: Install NGINX
    apt: 
      name: nginx
      state: latest

  - name: generage cs conf
    template:
      src: code-server.conf.j2
      dest: /etc/nginx/sites-available/code-server.conf

  - name: link code-server conf to sites-enabled
    file:
      src: /etc/nginx/sites-available/code-server.conf
      dest: /etc/nginx/sites-enabled/code-server.conf
      state: link

  - name: start NGINX
    systemd:
      name: nginx 
      state: restarted
